// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0qhlc7S_XGV_oIhmj6Gtd1Xh1Ph6Edmw',
    appId: '1:178029391219:web:4828dc625485ba98166906',
    messagingSenderId: '178029391219',
    projectId: 'login-b8801',
    authDomain: 'login-b8801.firebaseapp.com',
    storageBucket: 'login-b8801.appspot.com',
    measurementId: 'G-PPR0PYPFYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE-Fb0NhiVY02_pM8CDh7_eR_AsRdIvhw',
    appId: '1:178029391219:android:46f2550ef63cbab1166906',
    messagingSenderId: '178029391219',
    projectId: 'login-b8801',
    storageBucket: 'login-b8801.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmXBX3lV5Rafonl24kdrgtia6vk3_7KIA',
    appId: '1:178029391219:ios:f444cae366a5918a166906',
    messagingSenderId: '178029391219',
    projectId: 'login-b8801',
    storageBucket: 'login-b8801.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmXBX3lV5Rafonl24kdrgtia6vk3_7KIA',
    appId: '1:178029391219:ios:0f065f9c3dd49383166906',
    messagingSenderId: '178029391219',
    projectId: 'login-b8801',
    storageBucket: 'login-b8801.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
